name: My First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: check repo
        uses: actions/checkout@v5

      - name: list and read file
        run: |
         echo "My first github actions job"
         ls -ltra
         cat testfile
      - name: Generate ASCII Art work
        run: cowsay -f dragon "Run from cover,I am a DRAGON...RAWE">> dragon.txt
      #- name: List files
      #  run: ls
      #- name: read file from repo
      #  run: cat testfile
  secNd_job:
    runs-on: ubuntu-latest
    steps:
      - name: second_job
        run: echo "second machine run"



