name: Generate ASCII Artwork

on:
  push:

jobs:
  ascii_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: List Repo Files
        run: ls -ltra 
      - name: Execute ASCII script
        run: |
          chmod +x .github/workflows/as.sh
          ./.github/workflows/as.sh
