name: Generate ASCII Artwork

on:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Exicute Cowsay CMD
        run: cowsay -f dragon "Run for cover,i am a DRAGON... RAWR">>dragon.txtltra 
      - name: upload the Dragon
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt
         
           
          
  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: download the Dragon
        uses: actions/download-artifact@v5
        with:
          name: dragon-text-file
          

      - name: test file exists
        run: grep -i "dragon" dragon.txt
      
        
  Deploy:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: download the Dragon
        uses: actions/download-artifact@v5
        with:
          name: dragon-text-file
      - name: Read File
        run: cat dragon.txt

      - name: deploy
        run: echo Doploying ... ... .
      
